"""
Execution Plan Data Model Module.

Defines the structure of planning steps generated by the AI agent prior to modifying code.

JS/Node.js comparison:
- TS: `interface PlanStep { step_id: number; file_path: string; action: 'create'|'modify'|'delete'; prompt: string; }`
- Python: Uses `@dataclass` with `enum` or string literal types.
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Dict, Any


@dataclass
class PlanStep:
    """
    Represents a single atomic action within an execution plan.

    Attributes:
        step_id (int): Sequential identifier for the step.
        target_file (Path): Path of the file to modify or create.
        action (str): Action type ('CREATE', 'MODIFY', 'DELETE').
        description (str): Human-readable summary of what change will be made.
        instructions (str): Detailed instructions for the LLM code generator.
    """
    step_id: int
    target_file: Path
    action: str
    description: str
    instructions: str


@dataclass
class ExecutionPlan:
    """
    Complete execution plan generated for a user prompt.

    Attributes:
        user_prompt (str): The original task prompt provided by the user.
        summary (str): High-level overview of the plan strategy.
        steps (List[PlanStep]): List of individual steps to execute in sequence.
    """
    user_prompt: str
    summary: str = ""
    steps: List[PlanStep] = field(default_factory=list)

    def to_markdown(self) -> str:
        """
        Formats the plan into a markdown string representation.

        Returns:
            str: Markdown formatted string of the plan.

        TODO:
            Implement detailed markdown formatting for saving plan artifacts.
        """
        # Placeholder implementation
        return f"# Execution Plan\n\nPrompt: {self.user_prompt}\n\nSteps: {len(self.steps)}"
